version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
          name: Pre-Install tasks
      - run:
          command: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
          name: Install dotnet-skd-6.0
      - run:
          command: dotnet build
          name: build
      - run:
          name: export test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              echo 'export PATH="$PATH:/root/.dotnet/tools"' >> "$BASH_ENV"
              dotnet test --no-build --logger "trx"
      - run:
          command: |
              export PATH="$BASH_ENV"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
workflows:
  test_my_app:
    jobs:
      - build_and_test